package co.castle.player;

public class Consts
{
	public final static String C_BLOOD_THIRST = "BLOODTHIRST", C_WOLFMORPH = "WOLF_MORPH",
			C_WOLFMORPH2 = "WOLF_MORPH2", C_MYSTMORPH = "MYST_MORPH",
			C_MYSTMORPH2 = "MYST_MORPH2", C_BATMORPH = "BAT_MORPH",
			C_BATMORPH2 = "BAT_MORPH2", C_FIREBALL_WHIP = "FIREBALL_WHIP",
			C_WEAPON_ENCHANTMENT = "WEAPON_ENCHANTMENT", C_ENERGYSHIELD = "ENERGYSHIELD",
			C_MAGICLIGHT = "MAGICLIGHT", C_MONSTER_SLEEP = "MONSTER_SLEEP",
			C_SPELL_FIRE = "SPELL_FIRE", C_SPELL_ICE = "SPELL_ICE",
			C_SPELL_LIT = "SPELL_LIT", C_MONSTER_FREEZE = "MONSTER_FREEZE",
			C_TURTLESHELL = "TURTLESHELL", C_MONSTER_CHARM = "CHARM",
			C_BEASTMORPH = "BEASTMORPH", C_LUPINEMORPH = "LUPINEMORPH",
			C_BEARMORPH = "BEARMORPH", C_DEMONMORPH = "DEMONMORPH",
			C_WEREWOLFMORPH = "WEREWOLFMORPH", C_POWERBLOW = "C_POWERBLOW",
			C_POWERBLOW2 = "C_POWERBLOW2", C_POWERBLOW3 = "C_POWERBLOW3",
			F_SELFCONTROL = "F_SELFCONTROL", F_COMPLETECONTROL = "F_COMPLETECONTROL",

			ENV_RAIN = "ENV_RAIN", ENV_THUNDERSTORM = "ENV_THUNDERSTORN",
			ENV_FOG = "ENV_FOG", ENV_SUNNY = "ENV_SUNNY";

}
